# Generated by Django 5.2.17 on 2026-09-08 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('event_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('device_id', models.CharField(db_index=True, max_length=100)),
                ('room_id', models.CharField(db_index=True, max_length=100)),
                ('ts', models.DateTimeField(db_index=True, help_text='Canonical (earliest) fall timestamp')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('cursor', models.BigIntegerField(db_index=True, help_text='Position in the alarm feed')),
                ('duplicates_collapsed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['cursor'],
                'indexes': [models.Index(fields=['room_id', 'ts'], name='api_alarm_room_id_3a6252_idx')],
            },
        ),
    ]
